# state related information

state_fips_codes = {
    'Alabama': {'alpha_code': 'AL', 'numeric_code': '01', 'status': 'State'},
    'Alaska': {'alpha_code': 'AK', 'numeric_code': '02', 'status': 'State'},
    'American Samoa': {'alpha_code': 'AS',
                       'numeric_code': '60',
                       'status': 'Outlying area under U.S. sovereignty'},
    'American Samoa *': {'alpha_code': 'nan',
                         'numeric_code': '03',
                         'status': '(FIPS 5-1 reserved code)'},
    'Arizona': {'alpha_code': 'AZ', 'numeric_code': '04', 'status': 'State'},
    'Arkansas': {'alpha_code': 'AR', 'numeric_code': '05', 'status': 'State'},
    'Baker Island': {'alpha_code': 'nan',
                     'numeric_code': '81',
                     'status': 'Minor outlying island territory'},
    'California': {'alpha_code': 'CA', 'numeric_code': '06', 'status': 'State'},
    'Canal Zone *': {'alpha_code': 'nan',
                     'numeric_code': '07',
                     'status': '(FIPS 5-1 reserved code)'},
    'Colorado': {'alpha_code': 'CO', 'numeric_code': '08', 'status': 'State'},
    'Connecticut': {'alpha_code': 'CT', 'numeric_code': '09', 'status': 'State'},
    'Delaware': {'alpha_code': 'DE', 'numeric_code': '10', 'status': 'State'},
    'District of Columbia': {'alpha_code': 'DC',
                             'numeric_code': '11',
                             'status': 'Federal district[4]'},
    'Federated States of Micronesia': {'alpha_code': 'FM',
                                       'numeric_code': '64',
                                       'status': 'Freely Associated State'},
    'Florida': {'alpha_code': 'FL', 'numeric_code': '12', 'status': 'State'},
    'Georgia': {'alpha_code': 'GA', 'numeric_code': '13', 'status': 'State'},
    'Guam': {'alpha_code': 'GU',
             'numeric_code': '66',
             'status': 'Outlying area under U.S. sovereignty'},
    'Guam *': {'alpha_code': 'nan',
               'numeric_code': '14',
               'status': '(FIPS 5-1 reserved code)'},
    'Hawaii': {'alpha_code': 'HI', 'numeric_code': '15', 'status': 'State'},
    'Howland Island': {'alpha_code': 'nan',
                       'numeric_code': '84',
                       'status': 'Minor outlying island territory'},
    'Idaho': {'alpha_code': 'ID', 'numeric_code': '16', 'status': 'State'},
    'Illinois': {'alpha_code': 'IL', 'numeric_code': '17', 'status': 'State'},
    'Indiana': {'alpha_code': 'IN', 'numeric_code': '18', 'status': 'State'},
    'Iowa': {'alpha_code': 'IA', 'numeric_code': '19', 'status': 'State'},
    'Jarvis Island': {'alpha_code': 'nan',
                      'numeric_code': '86',
                      'status': 'Minor outlying island territory'},
    'Johnston Atoll': {'alpha_code': 'nan',
                       'numeric_code': '67',
                       'status': 'Minor outlying island territory'},
    'Kansas': {'alpha_code': 'KS', 'numeric_code': '20', 'status': 'State'},
    'Kentucky': {'alpha_code': 'KY', 'numeric_code': '21', 'status': 'State'},
    'Kingman Reef': {'alpha_code': 'nan',
                     'numeric_code': '89',
                     'status': 'Minor outlying island territory'},
    'Louisiana': {'alpha_code': 'LA', 'numeric_code': '22', 'status': 'State'},
    'Maine': {'alpha_code': 'ME', 'numeric_code': '23', 'status': 'State'},
    'Marshall Islands': {'alpha_code': 'MH',
                         'numeric_code': '68',
                         'status': 'Freely Associated State'},
    'Maryland': {'alpha_code': 'MD', 'numeric_code': '24', 'status': 'State'},
    'Massachusetts': {'alpha_code': 'MA',
                      'numeric_code': '25',
                      'status': 'State'},
    'Michigan': {'alpha_code': 'MI', 'numeric_code': '26', 'status': 'State'},
    'Midway Islands': {'alpha_code': 'nan',
                       'numeric_code': '71',
                       'status': 'Minor outlying island territory'},
    'Minnesota': {'alpha_code': 'MN', 'numeric_code': '27', 'status': 'State'},
    'Mississippi': {'alpha_code': 'MS', 'numeric_code': '28', 'status': 'State'},
    'Missouri': {'alpha_code': 'MO', 'numeric_code': '29', 'status': 'State'},
    'Montana': {'alpha_code': 'MT', 'numeric_code': '30', 'status': 'State'},
    'Navassa Island': {'alpha_code': 'nan',
                       'numeric_code': '76',
                       'status': 'Minor outlying island territory'},
    'Nebraska': {'alpha_code': 'NE', 'numeric_code': '31', 'status': 'State'},
    'Nevada': {'alpha_code': 'NV', 'numeric_code': '32', 'status': 'State'},
    'New Hampshire': {'alpha_code': 'NH',
                      'numeric_code': '33',
                      'status': 'State'},
    'New Jersey': {'alpha_code': 'NJ', 'numeric_code': '34', 'status': 'State'},
    'New Mexico': {'alpha_code': 'NM', 'numeric_code': '35', 'status': 'State'},
    'New York': {'alpha_code': 'NY', 'numeric_code': '36', 'status': 'State'},
    'North Carolina': {'alpha_code': 'NC',
                       'numeric_code': '37',
                       'status': 'State'},
    'North Dakota': {'alpha_code': 'ND', 'numeric_code': '38', 'status': 'State'},
    'Northern Mariana Islands': {'alpha_code': 'MP',
                                 'numeric_code': '69',
                                 'status': 'Outlying area under U.S. sovereignty'},
    'Ohio': {'alpha_code': 'OH', 'numeric_code': '39', 'status': 'State'},
    'Oklahoma': {'alpha_code': 'OK', 'numeric_code': '40', 'status': 'State'},
    'Oregon': {'alpha_code': 'OR', 'numeric_code': '41', 'status': 'State'},
    'Palau': {'alpha_code': 'PW',
              'numeric_code': '70',
              'status': 'Freely Associated State'},
    'Palmyra Atoll': {'alpha_code': 'nan',
                      'numeric_code': '95',
                      'status': 'Minor outlying island territory'},
    'Pennsylvania': {'alpha_code': 'PA', 'numeric_code': '42', 'status': 'State'},
    'Puerto Rico': {'alpha_code': 'PR',
                    'numeric_code': '72',
                    'status': 'Outlying area under U.S. sovereignty'},
    'Puerto Rico *': {'alpha_code': 'nan',
                      'numeric_code': '43',
                      'status': '(FIPS 5-1 reserved code)'},
    'Rhode Island': {'alpha_code': 'RI', 'numeric_code': '44', 'status': 'State'},
    'South Carolina': {'alpha_code': 'SC',
                       'numeric_code': '45',
                       'status': 'State'},
    'South Dakota': {'alpha_code': 'SD', 'numeric_code': '46', 'status': 'State'},
    'Tennessee': {'alpha_code': 'TN', 'numeric_code': '47', 'status': 'State'},
    'Texas': {'alpha_code': 'TX', 'numeric_code': '48', 'status': 'State'},
    'U.S. Minor Outlying Islands': {'alpha_code': 'UM',
                                    'numeric_code': '74',
                                    'status': 'Minor outlying island territories (aggregated)'},
    'Utah': {'alpha_code': 'UT', 'numeric_code': '49', 'status': 'State'},
    'Vermont': {'alpha_code': 'VT', 'numeric_code': '50', 'status': 'State'},
    'Virgin Islands of the U.S.': {'alpha_code': 'VI',
                                   'numeric_code': '78',
                                   'status': 'Outlying area under U.S. sovereignty'},
    'Virgin Islands of the U.S. *': {'alpha_code': 'nan',
                                     'numeric_code': '52',
                                     'status': '(FIPS 5-1 reserved code)'},
    'Virginia': {'alpha_code': 'VA', 'numeric_code': '51', 'status': 'State'},
    'Wake Island': {'alpha_code': 'nan',
                    'numeric_code': '79',
                    'status': 'Minor outlying island territory'},
    'Washington': {'alpha_code': 'WA', 'numeric_code': '53', 'status': 'State'},
    'West Virginia': {'alpha_code': 'WV',
                      'numeric_code': '54',
                      'status': 'State'},
    'Wisconsin': {'alpha_code': 'WI', 'numeric_code': '55', 'status': 'State'},
    'Wyoming': {'alpha_code': 'WY', 'numeric_code': '56', 'status': 'State'}
}
